### ISSUE TITLE
Change name & tip text

### ISSUE THREAD

**Issue by peterlee18** [awesome-panel/panel-modal#2]
Hi Marc, 

This panel_modal is perfect for my use case.

Is it possible to have the "Open" label to be configurable. and also the tip text "Trigger this to open the modal". In my use case, the modal opens up a file browser. So I would like button to be be labelled "Browse" and the tip text to say something like "Click to open file browser". But I'm sure there will be numerous use casesecah with their own labels and tip text.

Thanks

**Comment by MarcSkovMadsen** [comment]
Thanks for the nice feedback.

You can achieve what you are after by creating custom buttons with a `name="Browse"` and `description="Click to open file browser"`. The button should then trigger an opening of the Modal when clicked.

If you need further help try posting a minimum, reproducible example. Then its easy for me to add a custom button.

**Comment by peterlee18** [comment]
Ok got it. Use the mymodal.param.trigger("open") event, where mymodal is the Modal instance. 

Thanks Marc
